name: Aspect Workflows
description: |
  Delivers the promised 10x performance benefit of Bazel.
  Auto-scaling "warm" runners, remote cache & exec, CD and more.
branding:
  icon: triangle
  color: gray-dark
inputs:
  configuration:
    description: location of the Aspect Workflows config
    required: true
    default: .aspect/workflows/config.yaml
  workspace:
    description: path from the git repository to the WORKSPACE.bazel file
    required: true
    default: '.'
  task:
    description: the task that we want to generate steps for and then run
    required: true
  has_artifact_output:
    description: |
      Whether to expect upload_artifact_path= lines in the $GITHUB_OUTPUT file from rosetta.
      Equivalent to whether the task calls archiveArtifacts on the github.host.

runs:
  # Declare this is a "Composite Action"
  using: "composite"

  steps:

    # Simple wrapper around running rosetta
    - run: |
        rosetta run \
          --configuration ${{ inputs.configuration }} \
          --workspace ${{ inputs.workspace }} \
          ${{ inputs.task }}
      shell: bash
      id: rosetta-step

    # Uploads a zip file containing all archiveArtifact paths.
    # e.g. "test.artifacts.zip" will be in the Summary page on GHA UI.
    - name: Upload Artifact
      # Note, GHA will coerce boolean to string
      if: ${{ inputs.has_artifact_output == 'true' }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.task }}.artifacts
        path: ${{ steps.rosetta-step.outputs.upload_artifact_path }}
