name: Aspect Workflows CI

on:
  # Makes this workflow reusable, see
  # https://github.blog/2022-02-10-using-reusable-workflows-github-actions
  workflow_call:
    inputs:
      aspect-config:
        description: path to the Aspect Workflows config.yaml file
        type: string
        default: .aspect/workflows/config.yaml
      delivery-workflow:
        description: the name of the file which contains the delivery workflow
        type: string
        default: delivery.yaml
      queue:
        description: the queue / runner pool that the setup step will run on
        type: string
        default: default
    secrets:
      slack_webhook_url:
        description: if set, then a webhook notification will be sent for failing builds on a release branch

jobs:
  setup:
    runs-on: [self-hosted, aspect-workflows, "aspect-${{ inputs.queue }}"]
    steps:
      - uses: actions/checkout@v3
      - id: rosetta-generate
        run: |
          echo "json=$( \
            rosetta steps \
            --config ${{ inputs.aspect-config }} \
            --workspace . \
            --gha_task generate \
            --gha_json_pretty_print=false \
          )" | tee ${GITHUB_OUTPUT}

    outputs:
      cfg: ${{ steps.rosetta-generate.outputs.json }}

  bazel:
    needs: [setup]
    runs-on: ${{ fromJson(needs.setup.outputs.cfg).workflows_config[matrix.job].labels }}
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.cfg).matrix_config }}
    env:
      ASPECT_WORKFLOWS_CONFIG: ${{ inputs.aspect-config }}

    steps:
      - name: Configure environment
        run: configure_workflows_env

      - uses: actions/checkout@v3

      - name: Agent health checks
        run: agent_health_check

      - name: Branch Freshness
        uses: aspect-build/workflows-action@5.5.0-rc1
        with:
          workspace: ${{ fromJson(needs.setup.outputs.cfg).workflows_config[matrix.job].workspace }}
          task: branch_freshness

      - name: ${{ fromJson(needs.setup.outputs.cfg).workflows_config[matrix.job].task }}
        uses: aspect-build/workflows-action@5.5.0-rc1
        with:
            workspace: ${{ fromJson(needs.setup.outputs.cfg).workflows_config[matrix.job].workspace }}
            task: ${{ fromJson(needs.setup.outputs.cfg).workflows_config[matrix.job].task }}

      - name: Send notification to Slack workflow
        id: slack
        # oncall cares about branches that do delivery, so key this on whether we produce a delivery manifest
        if: failure() && fromJson(needs.setup.outputs.cfg).workflows_config[matrix.job].generate_manifest
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "gha_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}

      - name: Delivery Manifest
        if: fromJson(needs.setup.outputs.cfg).workflows_config[matrix.job].generate_manifest
        uses: aspect-build/workflows-action@5.5.0-rc1
        with:
            workspace: ${{ fromJson(needs.setup.outputs.cfg).workflows_config[matrix.job].workspace }}
            task: delivery_manifest
            has_artifact_output: true

      - name: Trigger Delivery 
        # This uses the following API: https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ inputs.delivery-workflow }}/dispatches \
            -d "{\"ref\":\"${{ fromJson(needs.setup.outputs.cfg).workflows_config[matrix.job].branch }}\",\"inputs\":{\"delivery_commit\":\"${GITHUB_SHA}\"}}"
        shell: bash
        if: fromJson(needs.setup.outputs.cfg).workflows_config[matrix.job].delivery
